local GAME_SPEED = Game.gameSpeed or 30

local CATEGORY = {
	NEUTRAL = 1,
	GOOD = 2,
	BAD = 3,
}

local CATEGORY_NAME = {
	[CATEGORY.NEUTRAL] = "Neutral",
	[CATEGORY.GOOD] = "Good",
	[CATEGORY.BAD] = "Bad",
}

return {
	PREFIX = "zk_cards",
	GAME_SPEED = GAME_SPEED,
	CATEGORY = CATEGORY,
	CATEGORY_NAME = CATEGORY_NAME,
	MAX_OFFERS_PER_DRAFT = 5,
	FIRST_DRAFT_FRAME = 60 * GAME_SPEED,
	SECOND_DRAFT_FRAME = 5 * 60 * GAME_SPEED,
	THIRD_DRAFT_FRAME = 10 * 60 * GAME_SPEED,
	REPEAT_DRAFT_INTERVAL_FRAMES = 10 * 60 * GAME_SPEED,
	VOTE_DURATION_FRAMES = 40 * GAME_SPEED,
	OFFERS_PER_DRAFT = 3,
	CATEGORY_WEIGHT_NEUTRAL = 1,
	CATEGORY_WEIGHT_GOOD = 1,
	CATEGORY_WEIGHT_BAD = 1,
}
