local constants = VFS.Include("LuaRules/Configs/Cards/card_constants.lua")
local CATEGORY = constants.CATEGORY

local defs = {
	{
		id = 101,
		name = "Meteor Shower",
		shortDescription = "Random meteors strike around allied finished units and buildings.",
		description = "Once picked, meteors periodically fall near your finished units and structures. Impact size, damage, and reclaim payout vary, and each strike leaves meteor scrap behind.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/areaattack.png",
		effectType = "meteor_shower",
	},
	{
		id = 102,
		name = "Metal Fuel",
		shortDescription = "Mobile units are cheaper, but movement burns metal and stalls on empty.",
		description = "Mobile units cost 90% less metal, but moving them consumes fuel based on travel distance and base unit cost. If your side cannot pay, moving units are heavily slowed until the next fuel check succeeds.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/metalplus.png",
		effectType = "metal_fuel",
	},
	{
		id = 103,
		name = "Energy Overload",
		shortDescription = "Singus overproduce energy while decaying faster and faster over time.",
		description = "Singularity reactors on your side gain escalating bonus energy output, starting at +100% and rising to +400% over 20 minutes. They also suffer escalating self-decay over time, from 2.5% to 25% max HP per second.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/energyplus.png",
		effectType = "energy_overload",
	},
	{
		id = 104,
		name = "Tanks",
		shortDescription = "Only tank factories survive; all other production factories are destroyed.",
		description = "Once picked, only Tank Foundries and Tank Plates may produce units for your side. Any other factory or factory plate you finish is immediately destroyed, and surviving forbidden factories are prevented from producing.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "tanks_only",
	},
	{
		id = 105,
		name = "Rapid Deployment",
		shortDescription = "Factories build much faster, but their mobile outputs are briefly disarmed.",
		description = "Allied factories and factory plates build units at triple speed. Mobile units finished from them are disarmed for 20 seconds when they roll off the line.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/repeat.png",
		effectType = "rapid_deployment",
	},
	{
		id = 106,
		name = "Frontier Economy",
		shortDescription = "Mexes boom when safe and slump when enemies pressure them.",
		description = "Allied metal extractors produce 25% more metal while no non-cloaked enemy units are nearby, but 25% less while contested.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/metalplus.png",
		effectType = "frontier_economy",
	},
	{
		id = 107,
		name = "Builders",
		shortDescription = "Builders generate metal, drain energy, and suppress mex income.",
		description = "All allied builders generate 0.4 metal per second while draining 1 energy per second, including factories and other non-factory builders. Allied metal extractors stop producing metal, and factories may only build constructors while no other mobile units may be built.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/repair.png",
		effectType = "builders",
	},
	{
		id = 108,
		name = "Nuclear Wildcard",
		shortDescription = "Trinity stockpiles free, fast nukes that fire at random targets.",
		description = "Allied Trinities stockpile missiles for free in 30 seconds. When fired, their chosen target point is replaced with a completely random in-map impact point.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/areaattack.png",
		effectType = "nuclear_wildcard",
	},
	{
		id = 109,
		name = "Strider Party",
		shortDescription = "Strider Hub mobile outputs are cheaper, smaller, and far frailer.",
		description = "All mobile units produced from the Strider Hub cost 40% as much, have only 20% max HP, and spawn at 40% visual size.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/repeat.png",
		effectType = "strider_party",
	},
	{
		id = 110,
		name = "Salvage Rights",
		shortDescription = "Wrecks and heaps contain more metal, stacking across picks.",
		description = "All unit wrecks and heaps on the map hold 50% more metal. If multiple allyteams pick this card, the bonus stacks additively across all wrecks on the battlefield.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/metalplus.png",
		effectType = "salvage_rights",
	},
	{
		id = 111,
		name = "Siege Doctrine",
		shortDescription = "Static positions reach farther while all mobile units slow down.",
		description = "All allied immobile units gain 50% weapon range and slower aiming response, while every allied mobile unit loses 25% move speed.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "siege_doctrine",
	},
	{
		id = 112,
		name = "Pre-Charged Shields",
		shortDescription = "Shields spawn massively overcharged, but never recharge afterward.",
		description = "Allied shields start with 10x their normal charge capacity when built, but shield recharge and shield-link sharing are disabled for those units afterward.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/repeat.png",
		effectType = "pre_charged_shields",
	},
	{
		id = 113,
		name = "Lobster Airlines",
		shortDescription = "Air transports become absurdly tough, but land units can only move by airlift.",
		description = "Charons and Herculeses on your side gain +1500% max HP. At the same time, allied land mobile units lose self-propelled movement and must rely on allied air transports to be repositioned.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/move.png",
		effectType = "lobster_airlines",
	},
	{
		id = 114,
		name = "Heavy Tanks",
		shortDescription = "Tank units become huge, tough multishot bruisers, but crawl forward slowly.",
		description = "Allied tank-factory mobile units lose 80% move speed, gain +200% max HP, double in size, and fire Tech-K style triple shots with each attack.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "heavy_tanks",
	},
	{
		id = 115,
		name = "Point Defense",
		shortDescription = "Weapons reload almost instantly, but rebuild their range over their original reload cycle.",
		description = "All non-stockpile allied weapons reset to 1% range immediately after firing, then recover smoothly back to full range over their original reload time. Their actual reload is reduced to near-instant while the card is active.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/attack.png",
		effectType = "point_defense",
	},
	{
		id = 201,
		name = "Raider Squads",
		shortDescription = "Built raiders split into five smaller unreclaimable squadmates.",
		description = "Once picked, newly built raiders are replaced by five mini raiders with 25% max HP, 40% size, and 20% value each. The minis cannot be reclaimed and leave no reclaimable debris.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/repeat.png",
		effectType = "raider_squads",
	},
	{
		id = 202,
		name = "Storage Mania",
		shortDescription = "Stored metal boosts allied metal extractor income.",
		description = "Your side gains a 1% bonus to metal extractor income for every full 250 metal currently held in storage, recalculated continuously from current reserves.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/metalplus.png",
		effectType = "storage_mania",
	},
	{
		id = 203,
		name = "Commanders",
		shortDescription = "Commanders gain major boosts to speed, range, build power, HP, and reload.",
		description = "All allied commanders gain +50% move speed, +50% attack speed, +30% weapon range, +100% build power, and +100% max HP. The bonus reapplies to commander upgrades and morph results.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/drop_beacon.png",
		effectType = "commanders",
	},
	{
		id = 204,
		name = "The Reclaimer",
		shortDescription = "Enemy kills refund full metal value and erase reclaimable wreckage.",
		description = "When an allied unit kills an enemy unit, the killer's team immediately gains the destroyed unit's full metal value. Destroyed enemy units killed this way leave no reclaimable wreck or heap behind.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/metalplus.png",
		effectType = "the_reclaimer",
	},
	{
		id = 205,
		name = "Reinforced Frames",
		shortDescription = "+5% max HP to completed allied units every minute.",
		description = "Once picked, every 60 seconds all currently fully constructed units on your side gain another additive 5% max HP bonus. Units do not receive missed past ticks retroactively.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/drop_beacon.png",
		effectType = "team_hp_growth",
	},
	{
		id = 206,
		name = "Emergency Reserves",
		shortDescription = "Resource crashes trigger short emergency income bursts.",
		description = "If allied metal or energy falls below 20% storage, that resource gains a 30 second +50% income burst. Metal and energy trigger separately and each has a ten minute cooldown.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/wait.png",
		effectType = "emergency_reserves",
	},
	{
		id = 207,
		name = "Hardened Logistics",
		shortDescription = "Static units get tougher and repair much faster.",
		description = "All allied immobile units gain 50% max HP, and finished immobile units repair in half the usual time.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/repair.png",
		effectType = "hardened_logistics",
	},
	{
		id = 208,
		name = "Field Repairs",
		shortDescription = "Idle mobile units regenerate after staying out of combat.",
		description = "Allied mobile units regenerate 1% of max HP per second after 10 seconds without taking damage, but only while command-idle and not disabled.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/repair.png",
		effectType = "field_repairs",
	},
	{
		id = 209,
		name = "Deep Magazines",
		shortDescription = "Burst weapons get larger salvos at the cost of slower reloads.",
		description = "Allied burst and magazine-style weapons gain 50% larger salvos or projectile counts, rounded up, but take 50% longer to reload between volleys.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/repeat.png",
		effectType = "deep_magazines",
	},
	{
		id = 210,
		name = "Lead the Charge",
		shortDescription = "Large same-type groups gain a buffed leader with a combat aura.",
		description = "When a team fields at least five finished mobile units of the same type, one becomes a Leader. Leaders gain huge combat bonuses and project a smaller range and reload aura to nearby allies of the same type. If the Leader dies, nearby matching units die too, and a replacement cannot be chosen for three minutes.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "lead_the_charge",
	},
	{
		id = 211,
		name = "Mega Lobster",
		shortDescription = "Lobsters become huge siege launchers that can throw buildings.",
		description = "Allied Lobsters gain +500% max HP, +100% size, and +100% range. While the card is active, their launcher may also throw allied and enemy buildings.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/move.png",
		effectType = "mega_lobster",
	},
	{
		id = 212,
		name = "Monopoly",
		shortDescription = "The top metal economy gains an additional 50% metal income.",
		description = "If your allyteam has the highest average metal income over the last three minutes, it receives an extra 50% metal income until another allyteam overtakes it.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/metalplus.png",
		effectType = "monopoly",
	},
	{
		id = 213,
		name = "Air Dominance",
		shortDescription = "Air units are slower but far tougher and rearm without landing.",
		description = "All allied air units lose 80% move speed but gain +200% max HP. Aircraft that normally need airpads rearm in the air instead of landing.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/fight.png",
		effectType = "air_dominance",
	},
	{
		id = 214,
		name = "Economy Pack",
		shortDescription = "Mex income shuts off while commander economy scales hard with level.",
		description = "Allied metal extractors stop producing metal. Instead, commanders scale from +4 metal and +6 energy income at level 1 up to +20/+20 income at level 20.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/metalplus.png",
		effectType = "economy_pack",
	},
	{
		id = 215,
		name = "Booster Jets",
		shortDescription = "Selected assault and riot units lunge forward and toughen briefly when engaging.",
		description = "Eligible allied ground assault and riot units, plus Dante, periodically ignite booster jets when they need to close distance. The boost lasts 4 seconds, shoves them forward, halves incoming damage, and then goes on a 30 second cooldown.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/fight.png",
		effectType = "booster_jets",
	},
	{
		id = 301,
		name = "Irreplacable Parts",
		shortDescription = "Repairs consume metal in proportion to health restored.",
		description = "Once picked, repairing completed allied units costs metal based on the fraction of HP restored. Repairs are clamped by how much metal your side can actually pay.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/repair.png",
		effectType = "irreplacable_parts",
	},
	{
		id = 302,
		name = "Energy Shortage",
		shortDescription = "Team energy output continuously swings between famine and surplus.",
		description = "Allied energy production oscillates over time, varying between 20% and 120% efficiency on a repeating cycle.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/energyplus.png",
		effectType = "energy_shortage",
	},
	{
		id = 303,
		name = "Fragile Munitions",
		shortDescription = "Weapons sometimes misfire, weakening the shot or jamming the shooter.",
		description = "Allied weapons occasionally misfire. Most misfires turn the shot into a dud that deals reduced damage, while rarer jams briefly disarm the firing unit outright.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/attack.png",
		effectType = "fragile_munitions",
	},
	{
		id = 304,
		name = "Corroded Armor",
		shortDescription = "Finished non-commander units steadily rot away over time.",
		description = "All finished allied non-commander units slowly lose health over time, draining 5% of their max HP per minute until repaired or destroyed.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "corroded_armor",
	},
	{
		id = 305,
		name = "Inefficient Refining",
		shortDescription = "Mexes are penalized unless they are heavily overdriven.",
		description = "Allied metal extractors run inefficiently while their overdrive stays below 150%, cutting their output until sufficient grid energy pushes them past the threshold.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/metalplus.png",
		effectType = "inefficient_refining",
	},
	{
		id = 306,
		name = "Battlefield Panic",
		shortDescription = "Nearby allied deaths spread temporary panic through the line.",
		description = "When an allied finished unit dies, nearby allied units briefly panic, usually suffering a short slow and occasionally being disarmed instead.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/wait.png",
		effectType = "battlefield_panic",
	},
	{
		id = 307,
		name = "Bounties",
		shortDescription = "Your prized units are exposed; killing them swings the economy.",
		description = "Every five minutes without an active bounty, a random allied finished unit or building worth at least 700 metal is marked and revealed in a nearby radius to all enemies. If it dies, all other allyteams gain a 30% economy boost for five minutes while your allyteam suffers a 50% economy penalty for three minutes.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "bounties",
	},
	{
		id = 308,
		name = "Knockback",
		shortDescription = "Firing powerful weapons throws the shooter backwards.",
		description = "Allied weapons generate recoil based on their base damage, applying knockback to the firing unit in the opposite direction of the shot.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/move.png",
		effectType = "knockback",
	},
	{
		id = 309,
		name = "Sleep",
		shortDescription = "Mobile units periodically fall asleep and become briefly inactive.",
		description = "Allied mobile units eventually grow tired, falling asleep for 30 seconds once every five minutes. Sleeping units cannot act, but regenerate a small amount of health while they rest.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/wait.png",
		effectType = "sleep",
	},
	{
		id = 310,
		name = "Be Careful",
		shortDescription = "If your last commander dies, the rest of your side dies too.",
		description = "When the final commander on your allyteam is destroyed, every remaining allied unit is destroyed as well.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/selfd.png",
		effectType = "be_careful",
	},
	{
		id = 311,
		name = "No Terraform",
		shortDescription = "Your team loses access to terraform commands.",
		description = "Allied constructors can no longer start new terraform projects. Existing terraform already in progress is left alone, but any new terraform orders are blocked outright.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/cancel.png",
		effectType = "no_terraform",
	},
}

local byID = {}
local idsByCategory = {
	[CATEGORY.NEUTRAL] = {},
	[CATEGORY.GOOD] = {},
	[CATEGORY.BAD] = {},
}

for i = 1, #defs do
	local def = defs[i]
	byID[def.id] = def
	idsByCategory[def.category][#idsByCategory[def.category] + 1] = def.id
end

return {
	defs = defs,
	byID = byID,
	idsByCategory = idsByCategory,
}
