local constants = VFS.Include("LuaRules/Configs/Cards/card_constants.lua")
local CATEGORY = constants.CATEGORY

local defs = {
	{
		id = 101,
		name = "Meteor Shower",
		shortDescription = "Random meteors strike around allied finished units and buildings.",
		description = "Once picked, meteors periodically fall near your finished units and structures. Impact size, damage, and reclaim payout vary, and each strike leaves meteor scrap behind.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/areaattack.png",
		effectType = "meteor_shower",
	},
	{
		id = 102,
		name = "Metal Fuel",
		shortDescription = "Mobile units are cheaper, but movement burns metal and stalls on empty.",
		description = "Mobile units cost 90% less metal, but moving them consumes fuel based on travel distance and base unit cost. If your side cannot pay, moving units are heavily slowed until the next fuel check succeeds.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/metalplus.png",
		effectType = "metal_fuel",
	},
	{
		id = 103,
		name = "Energy Overload",
		shortDescription = "Singus overproduce energy while decaying faster and faster over time.",
		description = "Singularity reactors on your side gain escalating bonus energy output, starting at +100% and rising to +400% over 20 minutes. They also suffer escalating self-decay over time, from 2.5% to 25% max HP per second.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/energyplus.png",
		effectType = "energy_overload",
	},
	{
		id = 104,
		name = "Tanks",
		shortDescription = "Only tank factories survive; all other production factories are destroyed.",
		description = "Once picked, only Tank Foundries and Tank Plates may produce units for your side. Any other factory or factory plate you finish is immediately destroyed, and surviving forbidden factories are prevented from producing.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "tanks_only",
	},
	{
		id = 105,
		name = "Signal Relay",
		shortDescription = "Extra neutral draft variety with no gameplay payload yet.",
		description = "Another neutral test card for draft variety and repeat filtering.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/repeat.png",
		effectType = "record_only",
	},
	{
		id = 106,
		name = "Paper Shield",
		shortDescription = "Looks defensive, currently does nothing except persist.",
		description = "A harmless neutral placeholder dressed up like a real tactical choice.",
		category = CATEGORY.NEUTRAL,
		image = "LuaUI/Images/commands/Bold/retreat.png",
		effectType = "record_only",
	},
	{
		id = 201,
		name = "Raider Squads",
		shortDescription = "Built raiders split into five smaller unreclaimable squadmates.",
		description = "Once picked, newly built raiders are replaced by five mini raiders with 25% max HP, 40% size, and 20% value each. The minis cannot be reclaimed and leave no reclaimable debris.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/repeat.png",
		effectType = "raider_squads",
	},
	{
		id = 202,
		name = "Storage Mania",
		shortDescription = "Stored metal boosts allied metal extractor income.",
		description = "Your side gains a 1% bonus to metal extractor income for every full 750 metal currently held in storage, recalculated continuously from current reserves.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/metalplus.png",
		effectType = "storage_mania",
	},
	{
		id = 203,
		name = "Commanders",
		shortDescription = "Commanders gain major boosts to speed, range, build power, HP, and reload.",
		description = "All allied commanders gain +50% move speed, +50% attack speed, +30% weapon range, +100% build power, and +100% max HP. The bonus reapplies to commander upgrades and morph results.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/drop_beacon.png",
		effectType = "commanders",
	},
	{
		id = 204,
		name = "The Reclaimer",
		shortDescription = "Enemy kills refund full metal value and erase reclaimable wreckage.",
		description = "When an allied unit kills an enemy unit, the killer's team immediately gains the destroyed unit's full metal value. Destroyed enemy units killed this way leave no reclaimable wreck or heap behind.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/metalplus.png",
		effectType = "the_reclaimer",
	},
	{
		id = 205,
		name = "Reinforced Frames",
		shortDescription = "+5% max HP to completed allied units every minute.",
		description = "Once picked, every 60 seconds all currently fully constructed units on your side gain another additive 5% max HP bonus. Units do not receive missed past ticks retroactively.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/drop_beacon.png",
		effectType = "team_hp_growth",
	},
	{
		id = 206,
		name = "Lucky Cache",
		shortDescription = "A simple positive placeholder to round out the pool.",
		description = "A simple beneficial placeholder included to keep the category pool healthy.",
		category = CATEGORY.GOOD,
		image = "LuaUI/Images/commands/Bold/ferry.png",
		effectType = "record_only",
	},
	{
		id = 301,
		name = "Irreplacable Parts",
		shortDescription = "Repairs consume metal in proportion to health restored.",
		description = "Once picked, repairing completed allied units costs metal based on the fraction of HP restored. Repairs are clamped by how much metal your side can actually pay.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/repair.png",
		effectType = "irreplacable_parts",
	},
	{
		id = 302,
		name = "Energy Shortage",
		shortDescription = "Team energy output continuously swings between famine and surplus.",
		description = "Allied energy production oscillates over time, varying between 20% and 120% efficiency on a repeating cycle.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/energyplus.png",
		effectType = "energy_shortage",
	},
	{
		id = 303,
		name = "Heavy Air",
		shortDescription = "A bad-card shell with no live penalty yet.",
		description = "A negative placeholder with no stat effect yet and full draft-system visibility.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/move.png",
		effectType = "record_only",
	},
	{
		id = 304,
		name = "Brittle Lines",
		shortDescription = "A fake downside card for offer-history testing.",
		description = "A fake downside card for UI and repeat-filter testing.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/patrol.png",
		effectType = "record_only",
	},
	{
		id = 305,
		name = "Cold Start",
		shortDescription = "A reserved penalty card that currently just persists.",
		description = "A detrimental placeholder card that keeps the bad pool deep enough for long matches.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/guard.png",
		effectType = "record_only",
	},
	{
		id = 306,
		name = "Lost Tempo",
		shortDescription = "A negative placeholder reserved for future permanent penalties.",
		description = "A bad-card placeholder reserved for future permanent penalties.",
		category = CATEGORY.BAD,
		image = "LuaUI/Images/commands/Bold/wait.png",
		effectType = "record_only",
	},
}

local byID = {}
local idsByCategory = {
	[CATEGORY.NEUTRAL] = {},
	[CATEGORY.GOOD] = {},
	[CATEGORY.BAD] = {},
}

for i = 1, #defs do
	local def = defs[i]
	byID[def.id] = def
	idsByCategory[def.category][#idsByCategory[def.category] + 1] = def.id
end

return {
	defs = defs,
	byID = byID,
	idsByCategory = idsByCategory,
}
